### ISSUE TITLE
客户端启动错误，错误信息: 请求被中止: 未能创建 SSL/TLS 安全通道。

### ISSUE THREAD

**Issue by Minecarft-YSY** [jsms2/jsmhToolChest#18]
**Bug描述:**
提示客户端启动错误，错误信息: 请求被中止: 未能创建 SSL/TLS 安全通道。
管理员模式运行也是的 4399盒子 XBS的端 防火墙关了

**截图:**
![image](https://github.com/jsms2/jsmhToolChest/assets/118052607/3047fbc2-897b-4dd7-8e94-3d6e1918ead8)
![image](https://github.com/jsms2/jsmhToolChest/assets/118052607/7621f815-0e7c-472a-807c-e0e929694cbc)

**设备信息:**
 - 系统版本: Windows 7旗舰版
 - 内部版本: 7601
![03917ccc713e3fd85e29d3293fda8e19](https://github.com/jsms2/jsmhToolChest/assets/118052607/4b01868e-a7fb-4697-8721-9fa944613dc7)
 - 系统类型: 64位操作系统
 - jsmhToolChest版本: 5.0B17
 - 网络环境: 中国电信

**Comment by jsms2** [comment]
使用Windows10即可

**Comment by Minecarft-YSY** [comment]
好的

**Comment by 11mc11** [comment]
一样win7不知道为啥hook就是不成功注入
