### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by jackerempty** [jsms2/jsmhToolChest#3]
PS D:\jsmhToolChest\jsmhToolChest> dotnet run
D:\jsmhToolChest\jsmhToolChest\jsmhToolChest.csproj(357,5): error : 这台计算机上缺少此 
项目引用的 NuG
et 程序包。使用“NuGet 程序包还原”可下载这些程序包。有关更多信息，请参见 http://go.microsoft.com/fwlink/?LinkID=32210
5。缺少的文件是 ..\packages\Fody.6.5.5\build\Fody.targets。

生成失败。请修复生成错误并重新运行。
PS D:\jsmhToolChest\jsmhToolChest> dotnet build
MSBuild version 17.5.0+6f08c67f3 for .NET
  正在确定要还原的项目…
  无可执行操作。指定的项目均不包含可还原的包。
D:\jsmhToolChest\jsmhToolChest\jsmhToolChest.csproj(357,5): error : 这台计算机上缺少此
项目引用的 NuG
et 程序包。使用“NuGet 程序包还原”可下载这些程序包。有关更多信息，请参见 http://go.microsoft.com/fwlink/?LinkID=32210
5。缺少的文件是 ..\packages\Fody.6.5.5\build\Fody.targets。

生成失败。

D:\jsmhToolChest\jsmhToolChest\jsmhToolChest.csproj(357,5): error : 这台计算机上缺少此 
项目引用的 NuG
et 程序包。使用“NuGet 程序包还原”可下载这些程序包。有关更多信息，请参见 http://go.microsoft.com/fwlink/?LinkID=32210
5。缺少的文件是 ..\packages\Fody.6.5.5\build\Fody.targets。
    0 个警告
    1 个错误

已用时间 00:00:00.34
PS D:\jsmhToolChest\jsmhToolChest> dotnet restore
  正在确定要还原的项目…
  无可执行操作。指定的项目均不包含可还原的包。

**Comment by jsms2** [comment]
自己去nuget包管理器下载一下包就行
