### ISSUE TITLE
移了目录就没法使用了？

### ISSUE THREAD

**Issue by xiaojiangxj233** [jsms2/jsmhToolChest#8]
![image](https://user-images.githubusercontent.com/109403149/232048543-9bd81124-b57a-455a-8dc5-dad796b7a229.png)
# 移了目录就没法使用了？

**Comment by tou002** [comment]
我也是这样

![~S6V8Y4~5S}8@W0K)(1VP 1](https://github.com/jsms2/jsmhToolChest/assets/102643572/20c50b1c-ac4c-4697-a2c3-610819f7b988)

**Comment by jsms2** [comment]
已经修复
